name = "senditfast"
compatibility_date = "2025-01-01"

[triggers]
crons = ["0 2 * * *"] # nightly

[vars]
B2_ENDPOINT = ""
B2_BUCKET = ""

# KV for lightweight sessions (optional)
# [[kv_namespaces]]
# binding = "SESSION_KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
